# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97017289d35c204bd2ff66226c4bb41fea2dba9bc001ae23ce4ada685735417f94f28bc2ee82eaa009b33ec36a85159dac460c4d03f96e63e54d1058356a20f1

test:
  secret_key_base: 408677adce38bf6233431c0428079af76fc6920a0fd1b19ab7ebb6a9f10dae886ab36c9bdf95330117bae1943c51d0e449f1cbcbd0c36d2e3791452706594512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
